services:
  main:
    image: ghcr.io/kelvpn/vpn4-prod:latest
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DATABASE_NAME=vpn
      - DATABASE_USER=vpn
      - DATABASE_PASSWORD=password
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - SECRET_KEY
      - ALLOWED_HOST
      - BOT_TOKEN

  redis:
    image: redis:7
    restart: unless-stopped
    hostname: redis

  postgres:
    image: postgres:15
    restart: unless-stopped
    hostname: postgres
    environment:
      POSTGRES_DB: vpn
      POSTGRES_USER: vpn
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data