apiVersion: v1
kind: ConfigMap
metadata:
  name: static-config
  namespace: vpn-prod
data:
  default.conf: |
    server {
      listen 80;

      location /static/ {
        alias /static/;
        access_log off;
        expires 30d;
        add_header Cache-Control "public";
      }
    }
