apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-refresh-keys
  namespace: vpn-prod
  labels:
    app: task-refresh-keys
spec:
  revisionHistoryLimit: 2
  replicas: 1
  selector:
    matchLabels:
      app: task-refresh-keys
  template:
    metadata:
      labels:
        app: task-refresh-keys
    spec:
      containers:
      - name: task-refresh-keys
        image: ghcr.io/kelvpn/vpn4-prod:latest
        args: [ "refresh_keys" , "10" ]
        env:
          - name: PYTHONUNBUFFERED
            value: "1"
        envFrom:
          - secretRef:
              name: app-secrets-prod
      imagePullSecrets:
        - name: github-registry-secret
